# Generated by Django 6.0.6 on 2026-06-28 22:28

import features.feedback.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_readinessrecord_accommodation_na_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(default=features.feedback.models._new_token, max_length=32, unique=True, verbose_name='token')),
                ('label', models.CharField(max_length=120, verbose_name='label')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_links', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'feedback link',
                'verbose_name_plural': 'feedback links',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='feedback.feedbacklink', verbose_name='link')),
            ],
            options={
                'verbose_name': 'feedback submission',
                'verbose_name_plural': 'feedback submissions',
                'ordering': ('-created_at',),
            },
        ),
    ]
