# Generated by Django 6.0.6 on 2026-06-28 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='help')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'intake panel',
                'verbose_name_plural': 'intake panels',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='IntakeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(max_length=60, verbose_name='stable key')),
                ('label', models.CharField(max_length=300, verbose_name='label')),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('bool', 'Yes/No'), ('date', 'Date'), ('number', 'Number'), ('select', 'Choice')], default='text', max_length=20, verbose_name='type')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='options')),
                ('requires_typed_negative', models.BooleanField(default=False, verbose_name='requires typed negative')),
                ('accepted_negatives', models.JSONField(blank=True, default=list, verbose_name='accepted negatives')),
                ('conditional_on', models.CharField(blank=True, max_length=60, verbose_name='conditional on')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='intake.intakepanel', verbose_name='panel')),
            ],
            options={
                'verbose_name': 'intake question',
                'verbose_name_plural': 'intake questions',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='IntakeQuestionnaireVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20, verbose_name='status')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='effective date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intake questionnaire version',
                'verbose_name_plural': 'intake questionnaire versions',
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='intakepanel',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='intake.intakequestionnaireversion', verbose_name='questionnaire'),
        ),
        migrations.CreateModel(
            name='RecruitmentIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='status')),
                ('current_panel_order', models.PositiveIntegerField(default=0, verbose_name='current panel')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='people.person', verbose_name='person')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='intake.intakequestionnaireversion', verbose_name='questionnaire')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recruitment intake',
                'verbose_name_plural': 'recruitment intakes',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='IntakeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('normalized_value', models.TextField(blank=True, verbose_name='normalized value')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='answered at')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='intake.intakequestion', verbose_name='question')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='intake.recruitmentintake', verbose_name='intake')),
            ],
            options={
                'verbose_name': 'intake answer',
                'verbose_name_plural': 'intake answers',
            },
        ),
        migrations.AddConstraint(
            model_name='intakequestion',
            constraint=models.UniqueConstraint(fields=('panel', 'stable_key'), name='unique_question_key_per_panel'),
        ),
        migrations.AddConstraint(
            model_name='intakequestionnaireversion',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_questionnaire_name_version'),
        ),
        migrations.AddConstraint(
            model_name='intakeanswer',
            constraint=models.UniqueConstraint(fields=('intake', 'question'), name='unique_answer_per_question'),
        ),
    ]
