# Generated by Django 6.0.6 on 2026-07-03 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_seed_inactive_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True, verbose_name='label')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'blacklist category',
                'verbose_name_plural': 'blacklist categories',
                'ordering': ('order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='BlacklistCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='proposed', max_length=20, verbose_name='status')),
                ('restricted_reason', models.TextField(blank=True, verbose_name='restricted reason')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_blacklist_cases', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blacklist_cases', to='people.person', verbose_name='person')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_blacklist_cases', to=settings.AUTH_USER_MODEL, verbose_name='proposed by')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='blacklist.blacklistcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'blacklist case',
                'verbose_name_plural': 'blacklist cases',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MatchFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('other', 'Other')], default='national_id', max_length=20, verbose_name='identifier type')),
                ('hmac', models.CharField(db_index=True, max_length=64, verbose_name='HMAC')),
                ('key_version', models.PositiveIntegerField(default=0, verbose_name='key version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='expires at')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='blacklist.blacklistcase', verbose_name='case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_fingerprints', to='people.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'match fingerprint',
                'verbose_name_plural': 'match fingerprints',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='blacklistcase',
            index=models.Index(fields=['status'], name='blacklist_b_status_c09447_idx'),
        ),
    ]
