# Generated by Django 6.0.6 on 2026-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfingerprint',
            name='identifier_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('name_dob_mmn', "Name + birth date + mother's maiden name"), ('other', 'Other')], default='national_id', max_length=20, verbose_name='identifier type'),
        ),
    ]
