# Generated by Django 6.0.6 on 2026-06-28 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='scheduled date')),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='state')),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('no_show', 'No-show')], default='pending', max_length=20, verbose_name='outcome')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('outcome_recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='outcome recorded at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_trials', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('outcome_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_trials', to=settings.AUTH_USER_MODEL, verbose_name='outcome recorded by')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='people.person', verbose_name='person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'trial assignment',
                'verbose_name_plural': 'trial assignments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReadinessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_state', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('not_applicable', 'Not applicable')], default='incomplete', max_length=20, verbose_name='medical')),
                ('gear_state', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('not_applicable', 'Not applicable')], default='incomplete', max_length=20, verbose_name='gear')),
                ('accommodation_state', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('not_applicable', 'Not applicable')], default='incomplete', max_length=20, verbose_name='accommodation')),
                ('transport_state', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('not_applicable', 'Not applicable')], default='incomplete', max_length=20, verbose_name='transport')),
                ('entry_medical_date', models.DateField(blank=True, null=True, verbose_name='entry medical date')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_records', to='people.person', verbose_name='person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_records', to='projects.project', verbose_name='project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_readiness', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'readiness record',
                'verbose_name_plural': 'readiness records',
                'constraints': [models.UniqueConstraint(fields=('person', 'project'), name='unique_readiness_per_person_project')],
            },
        ),
    ]
