# Generated by Django 6.0.6 on 2026-06-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_trialassignment_readinessrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinessrecord',
            name='accommodation_na_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='accommodation N/A reason'),
        ),
        migrations.AddField(
            model_name='readinessrecord',
            name='transport_na_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='transport N/A reason'),
        ),
    ]
