# Generated by Django 6.0.6 on 2026-06-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='first name')),
                ('last_name', models.CharField(max_length=120, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=200, verbose_name='place of birth')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='address')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='nationality')),
                ('preferred_language', models.CharField(blank=True, max_length=10, verbose_name='preferred language')),
                ('has_disability', models.BooleanField(default=False, verbose_name='has disability')),
                ('disability_type', models.CharField(blank=True, max_length=200, verbose_name='disability type')),
                ('lifecycle_status', models.CharField(choices=[('available', 'Available'), ('trial_day', 'Trial day'), ('working', 'Working'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='available', max_length=20, verbose_name='lifecycle status')),
                ('rehire_eligible', models.BooleanField(default=True, verbose_name='rehire eligible')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('search_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='search name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('owning_recruiter', models.ForeignKey(blank=True, help_text='The recruiter who entered this person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_people', to=settings.AUTH_USER_MODEL, verbose_name='owning recruiter')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ('last_name', 'first_name'),
                'indexes': [models.Index(fields=['lifecycle_status'], name='people_pers_lifecyc_0f9f35_idx')],
            },
        ),
    ]
