# Generated by Django 6.0.6 on 2026-06-28 13:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_trialassignment_readinessrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(verbose_name='month')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='revenue')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='cost')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('is_locked', models.BooleanField(default=False, verbose_name='locked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_months', to='projects.project', verbose_name='project')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_financial_months', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'financial month',
                'verbose_name_plural': 'financial months',
                'ordering': ('-year', '-month', 'project__name'),
                'constraints': [models.UniqueConstraint(fields=('project', 'year', 'month'), name='unique_financial_month_per_project')],
            },
        ),
    ]
