# Generated by Django 6.0.6 on 2026-08-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_financelineitem_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financecategory",
            name="key",
            field=models.SlugField(blank=True, max_length=60, verbose_name="key"),
        ),
    ]
