# Generated by Django 6.0.6 on 2026-06-29 10:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='label')),
                ('kind', models.CharField(choices=[('cost', 'Cost'), ('revenue', 'Revenue')], max_length=10, verbose_name='kind')),
                ('group', models.CharField(choices=[('labour', 'Labour'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('compliance', 'Compliance'), ('overhead', 'Overhead'), ('equipment', 'Equipment'), ('damage', 'Damage'), ('welfare', 'Welfare'), ('revenue', 'Revenue'), ('other', 'Other')], default='other', max_length=20, verbose_name='group')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'finance category',
                'verbose_name_plural': 'finance categories',
                'ordering': ('kind', 'order', 'label'),
                'constraints': [models.UniqueConstraint(fields=('label', 'kind'), name='unique_finance_category_label_kind')],
            },
        ),
        migrations.CreateModel(
            name='FinanceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='amount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='finance.financecategory', verbose_name='category')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.financialmonth', verbose_name='month')),
            ],
            options={
                'verbose_name': 'finance line item',
                'verbose_name_plural': 'finance line items',
                'ordering': ('category__kind', 'category__order'),
                'constraints': [models.UniqueConstraint(fields=('month', 'category'), name='unique_line_item_per_month_category')],
            },
        ),
    ]
