# Generated by Django 6.0.6 on 2026-07-27 20:04

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Attribute historical events to a person where it can be inferred.

    Without this the person filter still hides everything recorded before the
    column existed - which is the entire complaint - so the fix would look like
    it had not worked on any real database.

    Only two sources are safe to infer here: the target *was* the person, or a
    caller passed ``person`` in metadata (several already did). Walking every
    related model to find a ``.person`` is not possible from a historical
    model, so those rows stay unattributed and remain visible to everyone.
    """
    AuditEvent = apps.get_model("audit", "AuditEvent")
    Person = apps.get_model("people", "Person")
    known = set(Person.objects.values_list("pk", flat=True))

    rows = []
    for event in AuditEvent.objects.filter(person__isnull=True).only(
        "pk", "target_type", "target_id", "metadata"
    ):
        pk = None
        if event.target_type == "Person" and (event.target_id or "").isdigit():
            pk = int(event.target_id)
        else:
            raw = (event.metadata or {}).get("person")
            if isinstance(raw, int) or (isinstance(raw, str) and str(raw).isdigit()):
                pk = int(raw)
        if pk in known:
            event.person_id = pk
            rows.append(event)
    if rows:
        AuditEvent.objects.bulk_update(rows, ["person"], batch_size=500)


def unbackfill(apps, schema_editor):
    apps.get_model("audit", "AuditEvent").objects.update(person=None)


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        ("people", "0007_person_search_fold"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="people.person",
                verbose_name="person",
            ),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
