# Generated by Django 6.0.6 on 2026-07-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_totpdevice'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='staff', to='offices.office', verbose_name='offices'),
        ),
    ]
