# Generated by Django 6.0.6 on 2026-07-24 16:26

import core.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.media.avatar_upload_path, verbose_name='avatar'),
        ),
    ]
