# Generated by Django 6.0.6 on 2026-06-28 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='size')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'equipment item',
                'verbose_name_plural': 'equipment items',
                'ordering': ('name', 'size'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned')], default='issued', max_length=20, verbose_name='status')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued at')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='returned at')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_equipment', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_issues', to='people.person', verbose_name='person')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='logistics.equipmentitem', verbose_name='item')),
            ],
            options={
                'verbose_name': 'equipment issue',
                'verbose_name_plural': 'equipment issues',
                'ordering': ('-issued_at',),
            },
        ),
    ]
