# Generated by Django 6.0.6 on 2026-07-01 15:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_equipmentitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='monthly rate'),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rate override'),
        ),
    ]
