# Generated by Django 6.0.6 on 2026-07-01 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_room_monthly_rate_roomassignment_rate_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentissue',
            name='charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='charge amount'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='review_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='review note'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='review_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending review'), ('approved', 'Charge approved'), ('waived', 'Waived')], default='none', max_length=20, verbose_name='review status'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reviewed at'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_equipment_deductions', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
    ]
