# Generated by Django 6.0.6 on 2026-07-20 14:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_room_is_active_and_unique_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentissue',
            name='issued_stock_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='issued stock value'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='operation_key',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='operation key'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='return_disposition',
            field=models.CharField(blank=True, max_length=20, verbose_name='return disposition'),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='worker_payment_monthly',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='worker monthly payment'),
        ),
        migrations.CreateModel(
            name='EquipmentStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('return', 'Return'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='movement type')),
                ('occurred_on', models.DateField(verbose_name='occurred on')),
                ('quantity_delta', models.IntegerField(verbose_name='quantity delta')),
                ('value_delta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='value delta')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='logistics.equipmentissue', verbose_name='issue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='logistics.equipmentitem', verbose_name='item')),
            ],
            options={
                'ordering': ('occurred_on', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentStockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateField(verbose_name='received on')),
                ('initial_quantity', models.PositiveIntegerField(verbose_name='initial quantity')),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='initial value')),
                ('remaining_quantity', models.PositiveIntegerField(verbose_name='remaining quantity')),
                ('remaining_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='remaining value')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='logistics.equipmentitem', verbose_name='item')),
                ('inbound_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lot', to='logistics.equipmentstockmovement', verbose_name='inbound movement')),
            ],
            options={
                'ordering': ('received_on', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentStockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='operation key')),
                ('received_on', models.DateField(verbose_name='received on')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='reference')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='supplier')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_stock_receipts', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'ordering': ('-received_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentStockReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='total value')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipt_lines', to='logistics.equipmentitem', verbose_name='item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='logistics.equipmentstockreceipt', verbose_name='receipt')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentstockmovement',
            name='receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='logistics.equipmentstockreceiptline', verbose_name='receipt line'),
        ),
        migrations.CreateModel(
            name='AccommodationCostPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(verbose_name='effective month')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacity')),
                ('per_head_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='per-head monthly cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_periods', to='logistics.accommodation', verbose_name='accommodation')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_cost_periods', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'ordering': ('-effective_month', '-id'),
                'constraints': [models.UniqueConstraint(fields=('accommodation', 'effective_month'), name='unique_accommodation_cost_effective_month')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='value')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='logistics.equipmentstocklot', verbose_name='lot')),
                ('outbound_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='logistics.equipmentstockmovement', verbose_name='outbound movement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('outbound_movement', 'lot'), name='unique_stock_allocation_lot')],
            },
        ),
        migrations.AddConstraint(
            model_name='equipmentstockreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'item'), name='unique_item_per_stock_receipt'),
        ),
        migrations.AddConstraint(
            model_name='equipmentstockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='stock_movement_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='equipmentstockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_line__isnull', False)), fields=('movement_type', 'receipt_line'), name='unique_stock_movement_per_receipt_line_type'),
        ),
        migrations.AddConstraint(
            model_name='equipmentstockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('issue__isnull', False)), fields=('movement_type', 'issue'), name='unique_stock_movement_per_issue_type'),
        ),
    ]
