# Generated by Django 6.0.6 on 2026-07-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0009_equipmentissue_issued_stock_value_and_more"),
        ("offices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accommodations",
                to="offices.office",
                verbose_name="office",
            ),
        ),
    ]
