# Generated by Django 6.0.6 on 2026-07-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0010_accommodation_office"),
        ("offices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentstockallocation",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_allocations",
                to="offices.office",
                verbose_name="office",
            ),
        ),
        migrations.AddField(
            model_name="equipmentstocklot",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_lots",
                to="offices.office",
                verbose_name="office",
            ),
        ),
        migrations.AddField(
            model_name="equipmentstockmovement",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="offices.office",
                verbose_name="office",
            ),
        ),
        migrations.AddField(
            model_name="equipmentstockreceipt",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_receipts",
                to="offices.office",
                verbose_name="office",
            ),
        ),
    ]
