# Generated by Django 6.0.6 on 2026-06-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('partner', models.CharField(blank=True, max_length=200, verbose_name='partner')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='office')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('financial_reporting_eligible', models.BooleanField(default=True, verbose_name='financial reporting eligible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('responsible_coordinators', models.ManyToManyField(blank=True, related_name='coordinated_projects', to=settings.AUTH_USER_MODEL, verbose_name='responsible coordinators')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('assignment_reason', models.CharField(blank=True, max_length=300, verbose_name='assignment reason')),
                ('coordinator_snapshot', models.CharField(blank=True, max_length=300, verbose_name='coordinator snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='people.person', verbose_name='person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'project assignment',
                'verbose_name_plural': 'project assignments',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('person',), name='unique_active_assignment_per_person')],
            },
        ),
    ]
