# Generated by Django 6.0.6 on 2026-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_trialassignment_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='region'),
        ),
    ]
