# Generated by Django 6.0.6 on 2026-07-24 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('projects', '0005_project_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='region',
        ),
        # office was a free-text CharField; there's no sensible automatic
        # conversion from arbitrary strings to a real Office row (ADR 0026
        # Phase A), so this is an explicit drop-and-recreate, not an
        # AlterField type change the DB would have to cast.
        migrations.RemoveField(
            model_name='project',
            name='office',
        ),
        migrations.AddField(
            model_name='project',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='offices.office', verbose_name='office'),
        ),
    ]
