# Generated by Django 6.0.6 on 2026-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_activationapproval"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinessrecord",
            name="trial_waived",
            field=models.BooleanField(default=False, verbose_name="trial waived"),
        ),
    ]
