# Generated by Django 6.0.6 on 2026-06-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_equipmentitem_equipmentissue'),
        ('projects', '0002_trialassignment_readinessrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='week start')),
                ('headcount', models.PositiveIntegerField(default=0, verbose_name='headcount')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_weeks', to='projects.project', verbose_name='project')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transport_weeks', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'transport week',
                'verbose_name_plural': 'transport weeks',
                'ordering': ('-week_start',),
                'constraints': [models.UniqueConstraint(fields=('project', 'week_start'), name='unique_transport_week_per_project')],
            },
        ),
    ]
