# Generated by Django 6.0.6 on 2026-06-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_transportweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit price'),
        ),
    ]
