# Generated by Django 6.0.6 on 2026-07-03 13:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_equipmentissue_charge_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentissue',
            name='charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='charge amount'),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='monthly rate'),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='rate override'),
        ),
    ]
