# Generated by Django 6.0.6 on 2026-06-28 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='people.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ('expiry_date',),
            },
        ),
    ]
