# Generated by Django 6.0.6 on 2026-07-11 06:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_person_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-(0[1-9]|1[0-2])$', 'Use the YYYY-MM format.')], verbose_name='period')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='net amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent')),
                ('sent_to', models.EmailField(blank=True, max_length=254, verbose_name='sent to')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='people.person', verbose_name='person')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='sent by')),
            ],
            options={
                'verbose_name': 'payslip',
                'verbose_name_plural': 'payslips',
                'ordering': ('-period', 'person__last_name'),
                'constraints': [models.UniqueConstraint(fields=('person', 'period'), name='uniq_payslip_person_period')],
            },
        ),
    ]
