# Generated by Django 6.0.6 on 2026-06-28 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=40, verbose_name='from')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('provider_sid', models.CharField(blank=True, max_length=64, verbose_name='provider id')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received')),
            ],
            options={
                'verbose_name': 'inbound message',
                'verbose_name_plural': 'inbound messages',
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('body', models.TextField(verbose_name='body')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message template',
                'verbose_name_plural': 'message templates',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=40, verbose_name='to')),
                ('body', models.TextField(verbose_name='body')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20, verbose_name='status')),
                ('provider_sid', models.CharField(blank=True, max_length=64, verbose_name='provider id')),
                ('error', models.CharField(blank=True, max_length=300, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='people.person', verbose_name='person')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'outbound message',
                'verbose_name_plural': 'outbound messages',
                'ordering': ('-created_at',),
            },
        ),
    ]
