# Generated by Django 6.0.6 on 2026-07-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboundmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("blocked", "Blocked (recipient not allowed here)"),
                ],
                default="queued",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
