# Generated by Django 6.0.6 on 2026-08-02 17:26

import django.core.validators
import django.db.models.deletion
import features.messaging.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_alter_outboundmessage_status"),
        ("offices", "0001_initial"),
        ("people", "0008_person_email_opt_out"),
        ("projects", "0007_activationapproval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="title")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="location"
                    ),
                ),
                (
                    "wage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="wage",
                    ),
                ),
                (
                    "wage_unit",
                    models.CharField(
                        blank=True,
                        choices=[("hour", "per hour"), ("month", "per month")],
                        default="hour",
                        max_length=10,
                        verbose_name="wage unit",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="start date"),
                ),
                ("terms", models.TextField(blank=True, verbose_name="terms")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_offers",
                        to="offices.office",
                        verbose_name="office",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_offers",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "job offer",
                "verbose_name_plural": "job offers",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EmailBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new_offer", "New job offer"),
                            ("reminder", "Offer reminder"),
                            ("seasonal", "Seasonal campaign"),
                            ("closing", "Offer closing soon"),
                        ],
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "recipient_count",
                    models.PositiveIntegerField(default=0, verbose_name="recipients"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="messaging.joboffer",
                        verbose_name="job offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "email batch",
                "verbose_name_plural": "email batches",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OutboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new_offer", "New job offer"),
                            ("reminder", "Offer reminder"),
                            ("seasonal", "Seasonal campaign"),
                            ("closing", "Offer closing soon"),
                        ],
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="to"),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="language"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="subject"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="body")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked (not sent)"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=300, verbose_name="error"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="messaging.emailbatch",
                        verbose_name="batch",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="messaging.joboffer",
                        verbose_name="job offer",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="people.person",
                        verbose_name="person",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "outbound email",
                "verbose_name_plural": "outbound emails",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OfferEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new_offer", "New job offer"),
                            ("reminder", "Offer reminder"),
                            ("seasonal", "Seasonal campaign"),
                            ("closing", "Offer closing soon"),
                        ],
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=features.messaging.models.language_choices,
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="subject")),
                ("body", models.TextField(verbose_name="body")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offer_email_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "offer email template",
                "verbose_name_plural": "offer email templates",
                "ordering": ("kind", "language"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "language"),
                        name="uniq_offer_template_kind_language",
                    )
                ],
            },
        ),
    ]
