# Generated by Django 6.0.6 on 2026-08-08

import uuid

from django.db import migrations, models


def populate_request_tokens(apps, schema_editor):
    EmailBatch = apps.get_model("messaging", "EmailBatch")
    for batch in EmailBatch.objects.filter(request_token__isnull=True).iterator():
        batch.request_token = uuid.uuid4()
        batch.save(update_fields=["request_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_joboffer_emailbatch_outboundemail_offeremailtemplate")
    ]

    operations = [
        migrations.AddField(
            model_name="emailbatch",
            name="request_token",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_request_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="emailbatch",
            name="request_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
