# Generated by Django 6.0.6 on 2026-07-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True, verbose_name='label')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'inactive reason',
                'verbose_name_plural': 'inactive reasons',
                'ordering': ('order', 'label'),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='inactive_since',
            field=models.DateField(blank=True, null=True, verbose_name='inactive since'),
        ),
        migrations.AddField(
            model_name='person',
            name='inactive_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='people.inactivereason', verbose_name='inactive reason'),
        ),
    ]
