# Generated by Django 6.0.6 on 2026-07-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('people', '0005_person_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='offices.office', verbose_name='office'),
        ),
    ]
