# Generated by Django 6.0.6 on 2026-07-27 20:04

from django.db import migrations, models

from core.people.naming import fold_name


def backfill(apps, schema_editor):
    """Existing people have an empty fold column until this runs, so the new
    diacritic-insensitive search would find nobody who predates the field."""
    Person = apps.get_model("people", "Person")
    rows = []
    for person in Person.objects.all().only("pk", "first_name", "last_name"):
        person.search_fold = fold_name(f"{person.first_name} {person.last_name}")
        rows.append(person)
    if rows:
        Person.objects.bulk_update(rows, ["search_fold"], batch_size=500)


def unbackfill(apps, schema_editor):
    # Reversible by clearing: the column is derived, so nothing is lost.
    apps.get_model("people", "Person").objects.update(search_fold="")


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0006_person_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="search_fold",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="search fold"
            ),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
