# Generated by Django 6.0.6 on 2026-08-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0007_person_search_fold"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email_opt_out",
            field=models.BooleanField(default=False, verbose_name="no offer emails"),
        ),
    ]
