# Generated by Django 6.0.1 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intake", "0002_intakequestion_transient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakequestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("textarea", "Long text"),
                    ("bool", "Yes/No"),
                    ("date", "Date"),
                    ("number", "Number"),
                    ("select", "Choice"),
                ],
                default="text",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
