#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
from email.parser import Parser
from pathlib import Path
from zipfile import ZipFile


def wheel_metadata(path: Path) -> tuple[str, str]:
    with ZipFile(path) as wheel:
        metadata_name = next(name for name in wheel.namelist() if name.endswith(".dist-info/METADATA"))
        metadata = Parser().parsestr(wheel.read(metadata_name).decode("utf-8"))
    return metadata["Name"], metadata["Version"]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description="Write a hash-pinned requirements lock from downloaded wheels.")
    parser.add_argument("wheelhouse", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--python-image", required=True)
    args = parser.parse_args()

    records: list[tuple[str, str, str]] = []
    for wheel in sorted(args.wheelhouse.glob("*.whl")):
        name, version = wheel_metadata(wheel)
        records.append((name, version, sha256(wheel)))

    if not records:
        raise SystemExit(f"No wheels found in {args.wheelhouse}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as handle:
        handle.write("# Generated by scripts/write_requirements_lock.py; do not edit by hand.\n")
        handle.write(f"# Resolved in Docker image: {args.python_image}\n")
        handle.write("# Install with: python -m pip install --require-hashes -r <this-file>\n\n")
        for name, version, digest in sorted(records, key=lambda item: item[0].lower()):
            handle.write(f"{name}=={version} \\\n")
            handle.write(f"    --hash=sha256:{digest}\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
