# Generated by Django 6.0.6 on 2026-07-10 23:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_seed_inactive_reasons'),
        ('projects', '0003_readinessrecord_accommodation_na_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('cash_advance', 'Cash advance'), ('pay_deduction', 'Pay deduction'), ('pay_addition', 'Pay addition')], max_length=20, verbose_name='entry type')),
                ('category', models.CharField(choices=[('cash_advance', 'Cash advance'), ('clothing', 'Clothing'), ('footwear', 'Footwear'), ('equipment', 'Equipment'), ('medical', 'Medical'), ('travel_fuel', 'Travel / fuel'), ('other', 'Other')], max_length=20, verbose_name='category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('pay_effect', models.CharField(choices=[('none', 'No payroll effect'), ('deduct', 'Deduct from pay'), ('add', 'Add to pay')], max_length=10, verbose_name='pay effect')),
                ('settlement_status', models.CharField(choices=[('open', 'Open'), ('included', 'Included in cycle'), ('deducted', 'Settled with pay'), ('cancelled', 'Cancelled')], default='open', max_length=10, verbose_name='settlement')),
                ('entry_date', models.DateField(verbose_name='entry date')),
                ('cycle_key', models.CharField(blank=True, default='', help_text='20th-to-20th cycle the entry settles in, keyed by the end month (e.g. 2026-07).', max_length=7, verbose_name='cycle')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='entered by')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='people.person', verbose_name='person')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='projects.project', verbose_name='company / project')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='advances.ledgerentry', verbose_name='reversal of')),
            ],
            options={
                'verbose_name': 'ledger entry',
                'verbose_name_plural': 'ledger entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entry_date'], name='advances_le_entry_d_4fcdb5_idx'), models.Index(fields=['cycle_key'], name='advances_le_cycle_k_5015c2_idx')],
            },
        ),
    ]
