# Generated by Django 6.0.6 on 2026-07-10 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_seed_inactive_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('kind', models.CharField(choices=[('activation', 'Activation'), ('reactivation', 'Reactivation')], default='activation', max_length=20, verbose_name='kind')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'checklist template',
                'verbose_name_plural': 'checklist templates',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('critical', models.BooleanField(default=True, help_text='Critical items block activation; others only warn.', verbose_name='critical')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'checklist item template',
                'verbose_name_plural': 'checklist item templates',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PersonChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False, verbose_name='done')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='done at')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='done by')),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_items', to='checklists.checklistitemtemplate', verbose_name='item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='people.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'person checklist item',
                'verbose_name_plural': 'person checklist items',
                'ordering': ('item_template__order', 'item_template_id'),
                'constraints': [models.UniqueConstraint(fields=('person', 'item_template'), name='uniq_person_checklist_item')],
            },
        ),
    ]
