# Generated by Django 6.0.6 on 2026-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitemtemplate",
            name="help_text",
            field=models.TextField(
                blank=True,
                help_text="What must be true before this item is ticked. Shown as the item's tooltip.",
                verbose_name="help text",
            ),
        ),
    ]
