# Generated by Django 6.0.6 on 2026-07-18 05:46

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0004_person_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WageEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period", models.CharField(max_length=7, validators=[django.core.validators.RegexValidator("^\\d{4}-(0[1-9]|1[0-2])$", "Use the YYYY-MM format.")], verbose_name="period")),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))], verbose_name="gross amount")),
                ("currency", models.CharField(default="EUR", max_length=3, verbose_name="currency")),
                ("note", models.CharField(blank=True, max_length=200, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="created by")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wage_entries", to="people.person", verbose_name="person")),
            ],
            options={
                "verbose_name": "wage entry",
                "verbose_name_plural": "wage entries",
                "ordering": ("-period", "person__last_name"),
                "constraints": [models.UniqueConstraint(fields=("person", "period"), name="uniq_wage_person_period", violation_error_message="A wage is already recorded for this person and period.")],
            },
        ),
    ]
