# Generated by Django 6.0.6 on 2026-07-19 16:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advances', '0001_initial'),
        ('wage_ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovered_in_period', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-(0[1-9]|1[0-2])$', 'Use the YYYY-MM format.')], verbose_name='recovered in period')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wage_recoveries', to='advances.ledgerentry', verbose_name='advance')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
            ],
            options={
                'verbose_name': 'advance recovery',
                'verbose_name_plural': 'advance recoveries',
                'ordering': ('-recovered_in_period', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('advance',), name='uniq_active_recovery_per_advance', violation_error_message='This advance already has an active wage recovery.')],
            },
        ),
    ]
