# Generated by Django 6.0.6 on 2026-07-24 17:53

import core.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('FORKLIFT', 'Forklift'), ('CRANE', 'Crane'), ('WELDING', 'Welding'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.media.certificate_upload_path, verbose_name='document'),
        ),
    ]
