# Generated by Django 6.0.1 on 2026-07-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("accounts", "0002_totpdevice")]

    operations = [
        migrations.CreateModel(
            name="NotificationDismissal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_key", models.CharField(max_length=200, verbose_name="item key")),
                ("item_version", models.CharField(max_length=200, verbose_name="item version")),
                ("dismissed_at", models.DateTimeField(auto_now_add=True, verbose_name="dismissed at")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_dismissals", to=settings.AUTH_USER_MODEL, verbose_name="user")),
            ],
            options={
                "verbose_name": "notification dismissal",
                "verbose_name_plural": "notification dismissals",
                "indexes": [models.Index(fields=["user", "item_key"], name="notificatio_user_id_494362_idx")],
                "constraints": [models.UniqueConstraint(fields=("user", "item_key", "item_version"), name="unique_notification_dismissal_state")],
            },
        )
    ]
