# Generated by Django 6.0.6 on 2026-07-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('country', models.CharField(max_length=2, verbose_name='country')),
            ],
            options={
                'verbose_name': 'office',
                'verbose_name_plural': 'offices',
                'ordering': ('name',),
            },
        ),
    ]
